#!/usr/bin/env sh

# see: https://vuepress.vuejs.org/guide/deploy.html#github-pages

# abort on errors
set -e

yarn build

cd docs/.vuepress/dist

git init
git add --all
git commit -m 'chore: deploy'
git push -f git@github.com:chunksnbits/portfolio.git master:gh-pages

cd -
